// lib/roomsData.js
// AB = Attached Bathroom | CW = Common Washroom | CB = Common Bathroom

export const ROOMS_DATA = {

  // ─── BOYS HOSTELS ───────────────────────────────────────────

  'i-8-4-faizabad': {
    branchTitle: '98 Boys Hostel I-8/4',
    gender: 'boys',
    priceNote: 'Per person / per month. Meals, WiFi & electricity included.',
    rooms: [
      {
        id: 'fz-1',
        name: 'Single Cubical Room',
        bathroom: 'CW',
        capacity: 1,
        price: 27000,
        photo: '/images/rooms/i-8-4-faizabad/single-cubical.jpg',
        description: 'Private single cubical with curtain partition. Common washroom shared with few residents.',
        features: ['Single Bed', 'Study Table', 'Wardrobe', 'Common Washroom'],
      },
      {
        id: 'fz-2',
        name: 'Four Seater Room',
        bathroom: 'CW',
        capacity: 4,
        price: 20000,
        photo: '/images/rooms/i-8-4-faizabad/four-seater-cw.jpg',
        description: 'Spacious four-bed room with separate beds and wardrobes. Shared washroom on same floor.',
        features: ['4 Beds', 'Study Tables', 'Wardrobes', 'Common Washroom'],
      },
      {
        id: 'fz-3',
        name: 'Four Seater Room',
        bathroom: 'AB',
        capacity: 4,
        price: 22000,
        photo: '/images/rooms/i-8-4-faizabad/four-seater-ab.jpg',
        description: 'Four-bed room with attached private bathroom inside the room.',
        features: ['4 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
    ],
  },

  'i-8-4-main': {
    branchTitle: '526 Boys Hostel I-8/4',
    gender: 'boys',
    priceNote: 'Per person / per month. Meals, WiFi & electricity included.',
    rooms: [
      {
        id: 'mn-1',
        name: 'Single Cubical Room',
        bathroom: 'CW',
        capacity: 1,
        price: 27500,
        photo: '/images/rooms/i-8-4-main/single-cubical-v2.jpg',
        description: 'Private single cubical room. Most affordable private option at this branch.',
        features: ['Single Bed', 'Study Table', 'Wardrobe', 'Common Washroom'],
      },
      {
        id: 'mn-2',
        name: 'Two Seater Room',
        bathroom: 'CB',
        capacity: 2,
        price: 22000,
        photo: '/images/rooms/i-8-4-main/two-seater-cb-v2.jpg',
        description: 'Comfortable two-bed room with common bathroom.',
        features: ['2 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'mn-3',
        name: 'Three Seater Room',
        bathroom: 'CW',
        capacity: 3,
        price: 21000,
        photo: '/images/rooms/i-8-4-main/three-seater-cw-v2.jpg',
        description: 'Three-bed sharing room with common washroom facilities.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Common Washroom'],
      },
      {
        id: 'mn-4',
        name: 'Three Seater Room',
        bathroom: 'CB',
        capacity: 3,
        price: 21000,
        photo: '/images/rooms/i-8-4-main/three-seater-cb-v2.jpg',
        description: 'Three-bed sharing room with common bathroom.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'mn-5',
        name: 'Five Seater Room',
        bathroom: 'AB',
        capacity: 5,
        price: 21000,
        photo: '/images/rooms/i-8-4-main/five-seater-ab-v2.jpg',
        description: 'Large five-bed room with attached bathroom. Best value per person.',
        features: ['5 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
    ],
  },

  'i-11-1': {
    branchTitle: '307 Boys Hostel I-11/1',
    gender: 'boys',
    priceNote: 'Per person / per month. Meals, WiFi & electricity included.',
    rooms: [
      {
        id: 'i11-1',
        name: 'Three Seater Room',
        bathroom: 'AB',
        capacity: 3,
        price: 23000,
        photo: '/images/rooms/i-11-1/three-seater-ab.jpg',
        description: 'Premium three-bed room with attached private washroom. Newly renovated interiors.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Attached Washroom'],
      },
      {
        id: 'i11-2',
        name: 'Three Seater Room',
        bathroom: 'CW',
        capacity: 3,
        price: 21000,
        photo: '/images/rooms/i-11-1/three-seater-cw-a.jpg',
        description: 'Comfortable three-bed room sharing common washroom on same floor.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Common Washroom'],
      },
      {
        id: 'i11-3',
        name: 'Three Seater Room',
        bathroom: 'CW',
        capacity: 3,
        price: 21000,
        photo: '/images/rooms/i-11-1/three-seater-cw-b.jpg',
        description: 'Three-bed sharing room with common washroom. Ground floor option.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Common Washroom'],
      },
    ],
  },

  // ─── GIRLS HOSTELS ───────────────────────────────────────────

  'i-8-3-branch-1': {
    branchTitle: '129 Girls Hostel I-8/3',
    gender: 'girls',
    priceNote: 'Per person / per month. Meals, WiFi & electricity included. Female staff only.',
    rooms: [
      {
        id: 'g1-1',
        name: 'Single Room',
        bathroom: 'AB',
        capacity: 1,
        price: 34000,
        photo: '/images/rooms/i-8-3-branch-1/single-ab.jpg',
        description: 'Premium single room with attached private bathroom. Most private option for female students.',
        features: ['Single Bed', 'Study Table', 'Wardrobe', 'Attached Bathroom'],
        isTopPick: true,
      },
      {
        id: 'g1-2',
        name: 'Single / Cubical Room',
        bathroom: 'CW',
        capacity: 1,
        price: 27000,
        photo: '/images/rooms/i-8-3-branch-1/single-cubical-cw.jpg',
        description: 'Single cubical room with common washroom. Privacy at an affordable price.',
        features: ['Single Bed', 'Study Table', 'Wardrobe', 'Common Washroom'],
      },
      {
        id: 'g1-3',
        name: 'Two Seater Room',
        bathroom: 'AB',
        capacity: 2,
        price: 25000,
        photo: '/images/rooms/i-8-3-branch-1/two-seater-ab.png',
        description: 'Two-bed room with attached bathroom. Ideal for friends who want to share.',
        features: ['2 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
      {
        id: 'g1-4',
        name: 'Three Seater Room',
        bathroom: 'AB',
        capacity: 3,
        price: 23000,
        photo: '/images/rooms/i-8-3-branch-1/three-seater-ab.jpg',
        description: 'Three-bed room with attached bathroom.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
      {
        id: 'g1-5',
        name: 'Three Seater Room',
        bathroom: 'AB',
        capacity: 3,
        price: 22000,
        photo: '/images/rooms/i-8-3-branch-1/three-seater-ab-2.jpg',
        description: 'Three-bed room with attached bathroom. Second floor option.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
      {
        id: 'g1-6',
        name: 'Three Seater Room',
        bathroom: 'CB',
        capacity: 3,
        price: 20000,
        photo: '/images/rooms/i-8-3-branch-1/three-seater-cb.jpg',
        description: 'Three-bed room with common bathroom. Budget-friendly option.',
        features: ['3 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'g1-7',
        name: 'Four Seater Room',
        bathroom: 'AW',
        capacity: 4,
        price: 20000,
        photo: '/images/rooms/i-8-3-branch-1/four-seater-aw.jpg',
        description: 'Four-bed room with attached washroom.',
        features: ['4 Beds', 'Study Tables', 'Wardrobes', 'Attached Washroom'],
      },
      {
        id: 'g1-8',
        name: 'Four Seater Room',
        bathroom: 'CB',
        capacity: 4,
        price: 18000,
        photo: '/images/rooms/i-8-3-branch-1/four-seater-cb.jpg',
        description: 'Four-bed room with common bathroom. Best value for groups.',
        features: ['4 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'g1-9',
        name: 'Two Seater Room',
        bathroom: 'CB',
        capacity: 2,
        price: 22000,
        photo: '/images/rooms/i-8-3-branch-1/two-seater-cb.jpg',
        description: 'Two-bed room with common bathroom.',
        features: ['2 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'g1-10',
        name: 'Six Seater Room',
        bathroom: 'AB',
        capacity: 6,
        price: 17500,
        photo: '/images/rooms/i-8-3-branch-1/six-seater-ab.jpg',
        description: 'Large six-bed room with attached bathroom. Most economical option.',
        features: ['6 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
    ],
  },

  'i-8-3-branch-2': {
    branchTitle: '855 Girls Hostel I-8/3',
    gender: 'girls',
    priceNote: 'Per person / per month. Meals, WiFi & electricity included. Female staff only.',
    rooms: [
      {
        id: 'g2-1',
        name: 'Two Seater Room',
        bathroom: 'CB',
        capacity: 2,
        price: 22000,
        photo: '/images/rooms/i-8-3-branch-2/two-seater-cb.png',
        description: 'Two-bed room with common bathroom. Clean and well maintained.',
        features: ['2 Beds', 'Study Tables', 'Wardrobes', 'Common Bathroom'],
      },
      {
        id: 'g2-2',
        name: 'Four Seater Room',
        bathroom: 'CW',
        capacity: 4,
        price: 20000,
        photo: '/images/rooms/i-8-3-branch-2/four-seater.jpg',
        description: 'Spacious four-bed room with common washroom facilities.',
        features: ['4 Beds', 'Study Tables', 'Wardrobes', 'Common Washroom'],
      },
      {
        id: 'g2-3',
        name: 'Five Seater Room',
        bathroom: 'AB',
        capacity: 5,
        price: 19000,
        photo: '/images/rooms/i-8-3-branch-2/five-seater-ab.jpg',
        description: 'Five-bed room with attached bathroom. Most affordable option at this branch.',
        features: ['5 Beds', 'Study Tables', 'Wardrobes', 'Attached Bathroom'],
      },
    ],
  },
}

// Bathroom label helper
export const BATHROOM_LABELS = {
  AB:  { label: 'Attached Bath',    short: 'Attached', color: 'green'  },
  AW:  { label: 'Attached Washroom', short: 'Attached', color: 'green' },
  CW:  { label: 'Common Washroom',  short: 'Common',   color: 'gray'   },
  CB:  { label: 'Common Bathroom',  short: 'Common',   color: 'gray'   },
}

// Price formatter
export const formatPrice = (price) =>
  `PKR ${price.toLocaleString('en-PK')}`
